name: C/C++ CI

on:
  push:
    branches: 
      - 'c\+\+'
jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: setup
      run: make setup
    - name: make
      run: make
